version: 2
updates:
  - package-ecosystem: pip
    directory: /fastapi
    schedule:
      interval: weekly
    labels: [dependencies, python]

  - package-ecosystem: pip
    directory: /streamlit
    schedule:
      interval: weekly
    labels: [dependencies, python]

  - package-ecosystem: npm
    directory: /react
    schedule:
      interval: weekly
    labels: [dependencies, javascript]

  - package-ecosystem: docker
    directory: /fastapi
    schedule:
      interval: weekly
    labels: [dependencies, docker]

  - package-ecosystem: docker
    directory: /streamlit
    schedule:
      interval: weekly
    labels: [dependencies, docker]

  - package-ecosystem: docker
    directory: /react
    schedule:
      interval: weekly
    labels: [dependencies, docker]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, ci]
