services:
  fastapi:
    build: ./fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"   
    volumes:
      - ./fastapi:/app


  streamlit:
    build: ./streamlit
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - ./streamlit:/app
