apiVersion: v1
kind: Secret
metadata:
  name: purchases-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  SECRET_KEY: {{ .Values.fastapi.secretKey }}
  ADMIN_PASSWORD: {{ .Values.fastapi.adminPassword }}
