apiVersion: v1
kind: ConfigMap
metadata:
  name: purchases-config
  namespace: purchases
data:
  POSTGRES_DB: purchases
  DATABASE_URL: postgresql://postgres:postgres@postgres-service:5432/purchases
  API_URL: http://fastapi-service:8000
